service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
functions:
  createAuction:
    handler: src/handlers/auction/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuction:
    handler: src/handlers/auction/get-auction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  getAuctions:
    handler: src/handlers/auction/get-auctions.handler
    events:
      - http:
          method: GET
          path: /auctions

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: true
